name 'stepanstipl-inifile'
version '1.0.3'
source 'git://github.com/stepanstipl/puppet-inifile.git'
author 'Puppetlabs and Stepan Stipl'
description 'Resource types for managing settings in INI files'
summary 'Resource types for managing settings in INI files'
license 'Apache'
project_page 'https://github.com/stepanstipl/puppet-inifile'
